# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8944aa0a7ef0fab570d1f5f61643ae765b174918b240fec5406b970994e8bd1ffcac742a7d2d4b21bb628618e6ef0a54cc7d6931a6e38676089be4a3bfa008ce

test:
  secret_key_base: 9aa5b00c7525459a992c9070f080235f0472a1c3b1c4e085e4f3cd80bc65450a55a07b568c4d707a3988eb3d2625126a166c4d611ebddab99e043c0a08440062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
